variables:
  PHP_CS_STANDARD: "Drupal,DrupalPractice"
  EXTENSIONS: "php,module,theme,inc,install"
  MODULES_PATH: "web/modules/custom/"
  THEMES_PATH: "web/themes/custom/"

composer:
  stage: build
  script: composer install

phpstan:
  stage: validate
  needs:
    - composer
  script:
    - ./vendor/bin/phpcs --standard=$PHP_CS_STANDARD --extensions=$EXTENSIONS $MODULES_PATH $THEMES_PATH
  allow_failure: false

