name: Integrate

on: pull_request

jobs:
  composer:
    name: Composer install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php_version: ${{ vars.PHP_VERSION }}
          tools: composer:${{ vars.COMPOSER_VERSION }}

      - name: Install composer dependencies
        run: composer install
