name: Integrate

on: pull_request

jobs:
  composer:
    name: Composer install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ vars.PHP_VERSION }}
          tools: composer:${{ vars.COMPOSER_VERSION }}

      - name: Install composer dependencies
        run: composer install

  phpcs:
    name: PHP Code Standards
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
            php-version: ${{ vars.PHP_VERSION }}
            tools: composer:${{ vars.COMPOSER_VERSION }}

      - name: Install composer dependencies
        run: composer install

      - name: PHP Code Sniffer
        run: |
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }}..HEAD)
          echo "Changed files:"
          echo "$CHANGED_FILES"

